# Generated by Django 5.1.1 on 2024-11-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="status",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="user",
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="name",
            field=models.CharField(default="Hamza", max_length=255),
            preserve_default=False,
        ),
    ]
