# Generated by Django 5.1.1 on 2024-12-23 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 23, 22, 4, 10, 224402, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
