# Generated by Django 5.1.1 on 2024-12-23 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_attendancerecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 24, 3, 16, 28, 37241)
            ),
        ),
    ]
